### PR TITLE
Calculate and store goodness-of-fit values for source-extractions.

### PR DESCRIPTION
**Pull request by timstaley**
Addresses #409

### CODE REVIEW

**Comment by timstaley** [comment]
@AntoniaR, @ajstewart  if you get a chance you might want to take a look at 
https://github.com/transientskp/tkp/blob/906727fb44073a2546abd819706a82c1b0ea91b9/tkp/sourcefinder/fitting.py#L224, to see if it makes sense and if you have any better ideas.

**Comment by timstaley** [comment]
Oh and @gijzelaerr , this changes the extractedsource structures, so you'll likely need to rebase the sqlalchemy stuff over it when it's merged. Hopefully that's not too tricky (I think the changes are minimal) but let me know if it gets messy and you want a hand.

**Comment by gijzelaerr** [comment]
I'm not rewriting those queries so they should not conflict

Op vr 12 jun. 2015 18:49 schreef Tim Staley <notifications@github.com>:

**Comment by ajstewart** [comment]
@timstaley the goodness of fit function looks good to me! Thanks for looking into it.

**Pull request merged**
