### PR TITLE
Parallel Pyse

### PR DESCRIPTION
**Pull request by hughbg**
This replaces the old pull request and moves it onto a branch. It updates the files and I have added a basic unit test for the parallel functionality, which was a suggestion by Gijs and John agreed. 

**original Issues with more discussion**:
https://support.astron.nl/lofar_issuetracker/issues/5813
https://support.astron.nl/lofar_issuetracker/issues/4732

Old pull request which now shows "unknown repository": https://github.com/transientskp/tkp/pull/258. Because I deleted my repository and started again taking this stuff off the master branch which I should have done at the start.

### CODE REVIEW

**Comment by gijzelaerr** [comment]
build bot: PR request by user who is not whitelisted

**Comment by gijzelaerr** [comment]
build bot: PR request by user who is not whitelisted

**Comment by HannoSpreeuw** [comment]
@hughbg I will have to dive into this to investigate if code or concepts would still be useful. 
Perhaps somebody at ASTRON can provide me access to the archived issues.

But perhaps you could explain at which level you were trying to implement parallellisation through multiprocessing. Was it at the level of subimages?  Or processing multiple images in parallel, e.g. with one image per subband and multiple subbands?

**Comment by jdswinbank** [comment]
I asked at ASTRON. I think the original issues are long gone; sorry for that. Further, although Hugh is occasionally still active on GitHub, he's long since moved on to other activities and it seems pretty unlikely that — even if he has time and energy to engage with this discussion — he remembers details about what he was working on the better part of a decade ago.

My suggestion would be to briefly glance at the code here to see if there's anything you think seems usable, and if nothing jumps out just close the PR unmerged.

**Comment by AntoniaR** [comment]
I think Hugh was dividing images up as well as processing different images in parallel.

I agree with John, a quick glance through and otherwise close this PR.

**Comment by HannoSpreeuw** [comment]
I took some time to look at it; it is not so hard to comprehend.
Parallellisation through `multiprocessing` is implemented using `Queue()` at three levels:
1) kappa, sigma clipping through `process_rows`, so determining the background characteristics per row of subimages.
2) Setting up the islands per an appropriate range of labels using `process_labels`; those labels were derived through connected component labelling.
3) Measuring the source properties per an appropriate range of islands through `process_islands`.
So queues and processes are generated at three instances. This takes about 1 second each time, in my experience. 
There is not really an easy way around this because source extraction is not " naturally parallel": it is straighforward to divide up an image into subimages, but sources near the edges of the subimages cause difficulties. So it is hard to propagate the same processes or threads through all steps of source extraction.

I expect this would have speeded up the code from a decade ago. But not the current code, because the 3 times 1s overhead from creating the processes is too large.

This PR does not seem to address the processing of multiple images in parallel; the parallellisation is implemented only at the image level.

**Comment by AntoniaR** [comment]
Thank you for having a read through to check if there is anything applicable to the latest version. Let's close this pull request.

**Pull request closed without merging**
