### PR TITLE
Fix inject.py file check

### PR DESCRIPTION
**Pull request by ajstewart**
Fixed missing brackets around file check logic. Otherwise a directory (i.e. CASA file) would never be found when using tkp-inject.py.

### CODE REVIEW

**Comment by gijzelaerr** [comment]
build bot: PR request by user who is not whitelisted

**Comment by gijzelaerr** [comment]
build bot: PR request by user who is not whitelisted

**Comment by gijzelaerr** [comment]
build bot: PR request by user who is not whitelisted

**Comment by gijzelaerr** [comment]
add to whitelist

**Comment by timstaley** [comment]
Thanks @ajstewart! Looks fine, I'm going to add a unit-test as it turns out we only test for fits-header injection, currently. I'm guessing you've already tested this manually?

**Comment by gijzelaerr** [comment]
ok to test

**Comment by timstaley** [comment]
Rebased as #425 with some added unit-testing and tweaks.

**Pull request closed without merging**
