### PR TITLE
read db config for deldataset

### PR DESCRIPTION
**Pull request by gijzelaerr**
fix issue #539

### CODE REVIEW

**Comment by mkuiack** [comment]
Are you sure it is reading all infomation? 
user =  'mkuiack'   in ~/PycharmProjects/tkp/traptest/pipeline.cfg

```python 
kuiack@Marks-MacBook-Pro-2:~/PycharmProjects/tkp/traptest
$ trap-manage.py deldataset 1 -y
Traceback (most recent call last):
  File "/usr/local/bin/trap-manage.py", line 4, in <module>
    __import__('pkg_resources').run_script('tkp==4.0rc1', 'trap-manage.py')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/tkp-4.0rc1-py2.7.egg/EGG-INFO/scripts/trap-manage.py", line 10, in <module>
    tkp.management.main()
  File "/usr/local/lib/python2.7/site-packages/tkp-4.0rc1-py2.7.egg/tkp/management.py", line 361, in main
    args.func(args)
  File "/usr/local/lib/python2.7/site-packages/tkp-4.0rc1-py2.7.egg/tkp/management.py", line 257, in deldataset
    dataset = db.session.query(Dataset).filter(Dataset.id==options.id).one()
  File "build/bdist.macosx-10.10-x86_64/egg/sqlalchemy/orm/query.py", line 2473, in one
  File "build/bdist.macosx-10.10-x86_64/egg/sqlalchemy/orm/query.py", line 2516, in __iter__
  File "build/bdist.macosx-10.10-x86_64/egg/sqlalchemy/orm/query.py", line 2529, in _execute_and_instances
  File "build/bdist.macosx-10.10-x86_64/egg/sqlalchemy/orm/query.py", line 2520, in _connection_from_session
  File "build/bdist.macosx-10.10-x86_64/egg/sqlalchemy/orm/session.py", line 882, in connection
  File "build/bdist.macosx-10.10-x86_64/egg/sqlalchemy/orm/session.py", line 887, in _connection_for_bind
  File "build/bdist.macosx-10.10-x86_64/egg/sqlalchemy/orm/session.py", line 334, in _connection_for_bind
  File "build/bdist.macosx-10.10-x86_64/egg/sqlalchemy/engine/base.py", line 2039, in contextual_connect
  File "build/bdist.macosx-10.10-x86_64/egg/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect
  File "build/bdist.macosx-10.10-x86_64/egg/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection
  File "build/bdist.macosx-10.10-x86_64/egg/sqlalchemy/util/compat.py", line 199, in raise_from_cause
  File "build/bdist.macosx-10.10-x86_64/egg/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
  File "build/bdist.macosx-10.10-x86_64/egg/sqlalchemy/pool.py", line 376, in connect
  File "build/bdist.macosx-10.10-x86_64/egg/sqlalchemy/pool.py", line 713, in _checkout
  File "build/bdist.macosx-10.10-x86_64/egg/sqlalchemy/pool.py", line 480, in checkout
  File "build/bdist.macosx-10.10-x86_64/egg/sqlalchemy/pool.py", line 1151, in _do_get
  File "build/bdist.macosx-10.10-x86_64/egg/sqlalchemy/pool.py", line 323, in _create_connection
  File "build/bdist.macosx-10.10-x86_64/egg/sqlalchemy/pool.py", line 449, in __init__
  File "build/bdist.macosx-10.10-x86_64/egg/sqlalchemy/pool.py", line 607, in __connect
  File "build/bdist.macosx-10.10-x86_64/egg/sqlalchemy/engine/strategies.py", line 97, in connect
  File "build/bdist.macosx-10.10-x86_64/egg/sqlalchemy/engine/default.py", line 385, in connect
  File "/usr/local/lib/python2.7/site-packages/psycopg2-2.6.1-py2.7-macosx-10.10-x86_64.egg/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "kuiack"
FATAL:  password authentication failed for user "kuiack"
```

**Comment by gijzelaerr** [comment]
i'm not sure why the m is dropped from your username, maybe you have some formatting error in your pipeline config?

**Comment by mkuiack** [comment]
My username on my laptop is 'kuiack' so that is the default in pipeline.cfg, but I changed it. 
```python
[database]
engine = 'postgresql'           ; or monetdb
database = 'Full_16SB'                   ; for example: 'kuiack'
user =  'mkuiack'                      ; for example: 'kuiack'
```

**Comment by gijzelaerr** [comment]
my pipeline:
```
[database]
engine = postgresql
database = markmark
user = markmarkmark
host = markmarkmarkmark
```
and when i run deldataset:

```
$  ../tkp/.virtualenv/bin/trap-manage.py deldataset 1

This script will delete dataset 1 with these settings:

	engine:     postgresql
	database:   markmark
	user:       markmarkmark
	password:   markmarkmark
	host:       markmarkmarkmark
	port:       5432

Are you sure you want to delete dataset 1? [y/N]: 
```

**Comment by gijzelaerr** [comment]
is this working now? if so you can accept the PR

**Comment by mkuiack** [comment]
yeah this works great! great job!

**Pull request merged**
