### PR TITLE
Accessors abstract attributes

### PR DESCRIPTION
**Pull request by timstaley**
A restructuring of how we define the abstract interface for DataAccessor.
Lots of detail in the commit logs.

### CODE REVIEW

**Comment by timstaley** [comment]
@gijzelaerr Hopefully this will satisfy your needs, have a look and let me know what you think.

**Comment by timstaley** [comment]
@gijzelaerr Hopefully this will satisfy your needs, have a look and let me know what you think.

**Comment by timstaley** [comment]
@gijzelaerr Hopefully this will satisfy your needs, have a look and let me know what you think.

**Comment by gijzelaerr** [comment]
Ok I've been reading this for a while now, just wanted to check - it looks like you took my PR without the AARTFAAC support, enhanced/rebased it to use meta classes, updated the doc and fixed the last sphinx problems, right?

**Comment by gijzelaerr** [comment]
I don't see the loss of the read-only properties as a problem. This is just how Python works, and trying to outsmart that is often going to hurt you in the future.

**Comment by gijzelaerr** [comment]
> this means that they have to return their values and makes it
> absolutely clear in the __init__ function which attributes are being
> initialized by which function (my worry with the alternative is that you end
>  up having to search through the whole inheritance stack to find the relevant
> function which has the side-effect of setting a particular attribute).

Hm, I find this an interesting solution. But the problem you describe is a general problem with Python and OO, not just how we use it. This is why you should keep you inheritance tree shallow.

You will run into problems if you want to use your method and want to access the state of the object in such a method, so this only works if the state is not required.

By the way, Pycharm helps a bit with OO, you can navigate the inheritance tree and  see where a variable is or should be defined.

**Comment by timstaley** [comment]
Re: Shallow inheritance trees and perils of OO - agreed, totally (see also - sourcefinder internals, lol). Not suggesting we try to adopt this coding style in general. But I figured I'd keep the functional style for now, since it fits the problem so far (use part of data, build an attribute, seems reasonably natural). It's also a section the of codebase where we'd like external contributors to chip in, so having it as easy to decipher as possible is a bonus (is this easy to read, or am I just biased?).

**Comment by gijzelaerr** [comment]
I think just having a class with methods modifying internal states is easier to grasp than this weird, hacky and scary `@` syntax to define a static class if I put on my naive astronomy glasses.

**Comment by timstaley** [comment]
Think I'll rebase the docfixes into one commit.

**Pull request closed without merging**
