### PR TITLE
vacuum before _flag_many_to_many_tempruncat

### PR DESCRIPTION
**Pull request by gijzelaerr**
Vacuum before running the _flag_many_to_many_tempruncat() query. 
(Addresses #432)
Can't really test this, so no tests.

When we find more places where it is a good idea to execute a vacuum I'll move this to `tkp.db`, but for now I leave it here.

### CODE REVIEW

**Comment by timstaley** [comment]
Hey @gijzelaerr , this looks good but I'd prefer the vacuum code to be in a function of its own, to keep things clear. I'll push that up now. I also wanted to ask how you determined where exactly to run the VACUUM ANALYZE - i.e. it's currently after we insert into temprunningcatalog, but before we flag many-to-many assocs. Is this arbitrary? Could we just run it after we empty the temprunningcatalog, or before the initial insert?

**Comment by gijzelaerr** [comment]
if you make it a function I would move it to tkp.db.database and let is accept a table name as argument. But that is probably just style.

My rationale was that the _flag_many_to_many_tempruncat() got stuck, which only touches `temprunningcatalog`, that is why I do the vaccuum before the `_flag_many_to_many_tempruncat`.

I didn't really do profiling, but I did see this this week:

http://vlo.science.uva.nl/munin/science.uva.nl/vlo.science.uva.nl/postgres_querylength_ALL.html

query length was growing (query getting 'stuck'), and since antonia uses the vaccuum branch that didn't happen anymore.

Will add a comment to the function, good point.

**Comment by timstaley** [comment]
OK yep, that makes sense.

**Comment by timstaley** [comment]
Rebased as #441

**Pull request closed without merging**
